dist: trusty
sudo: required

language: node_js
node_js:
  - "12.13.0"

first:
- export CHROME_BIN=chromium-browser

before_script:
- cd frontend
- npm install -g @angular/cli

script:
- npm install
- npm run test --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox --exit

