dist: trusty
sudo: required

language: node_js
node_js:
  - "12.13.0"

first:
- export CHROME_BIN=chromium-browser

before_script:
- cd frontend
- npm install -g @angular/cli

script:
- npm install
- npm run test --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL

